### ISSUE TITLE
Logitech g203 not working properly

### ISSUE THREAD

**Issue by RGBfan101** [rgb-master-team/RGBMaster#17]
Hello RGB Master Team, 
I'm having this issue with a Logitech device

Device: Logitech G203
Logitech G HUB version: 2020.8.5950
RGBMaster:  Latest release 2.1

- Music Sync effect seems to work but its kind of buggy, maybe not related to this device.
- Dominant color sync effect turn off the lights on the device and just don't do anything else.
- Cursor color effect works **but only change to the colors mentioned in the next point**.
- Color picker effect only turn lights to red, blue and green, the other colors just down take effect on the device.

Thank you (:

**Comment by deankevorkian** [comment]
Hey! I discovered this bug and reproduced it on my own G502.
This happened due to messing up the calculation of each color percentage and possible values were only 0% or 100%...
I believe this would also affect on music sync, dominant color and cursor effects as well.
I'll put the hotfixed version tomorrow and publish it

**Comment by deankevorkian** [comment]
@RGBfan101 See our [new release](https://github.com/rgb-master-team/RGBMaster/releases/tag/2.2).

**Comment by RGBfan101** [comment]
Thank you so much!

**Comment by deankevorkian** [comment]
Sure, let us know how it works for you!
