### ISSUE TITLE
Thank you, for finally building what I've been waiting for.

### ISSUE THREAD

**Issue by Darkwolf1515** [rgb-master-team/RGBMaster#21]
(yes its not an issue but this page lacks the discussion feature.) For years I've been wasting for true, cross device, open source, RGB software, and its finally here. Cant wait for Corsair support so I can disable all the software on start up and just have this. Thank you for finally creating a true core piece of software. :)

(Oh, and it uses that beautiful uwp style too, another bonus.)

**Comment by deankevorkian** [comment]
Thanks for stopping by and supporting! And yeah, the beautiful UWP style - we'll have to think what to do when we go cross-platform (we do plan on targetting Linux and Mobile with .NET 6 or project Uno). We wanted to have the UWP style without being a UWP app (since a UWP app restricts usage of many of the things we use in the app, like listening to the output of music) which complicated some things and required us to have a more "complex" architecture.
