### ISSUE TITLE
Minimize to tray option.

### ISSUE THREAD

**Issue by Darkwolf1515** [rgb-master-team/RGBMaster#25]
Would be nice to put it in the tray when not in use.

**Comment by benbense** [comment]
After investigating, an implementation for this option currently is not available.
UWP wont allow us to use the minimize to tray option, that is because future Windows platform abandoned that feature (e.g. Windows 10X), as if that option will be back we will gladly add it to the app.
We have tried to implement Jump Lists but after giving it some test we have decided that it is not suitable for the app's user experience. 
Thanks a lot for giving us advices on how to develop and make the app greater.

**Comment by Darkwolf1515** [comment]
Maybe I'm wrong, but im certain that I have uwp apps that minimize to the tray, eartrumpet and bitwarden, both from the ms store.

**Comment by deankevorkian** [comment]
Bitwarden is in written in Electron and is not a UWP AFAIK. Eartrumpet is WPF AFAIK.
Our app is actually a-WPF that uses UWP for the UI via a rather experimental feature called Xaml Islands.
Microsoft has not provided an integrated way of minimizing an app to the taskbar, on both UWP and WPF, and is not planning to; there's a "workaround" that allows those apps to do this by hosting a Form application that communicates with the original application, complicating our architecture for things that we don't believe are worth it. It also seems like Microsoft is slowly trying to move people from hiding to the taskbar to using the jump list in Windows 10x... You see, we already use 2 technologies that interact with another just for the sake of a good looking UI. Adding a third one to the chain, isn't worth it in my eyes...

So we went and tried the JumpList (right clicking icons on the task menu, whether they are open or closed). Microsoft features a great and comfortable API for that (although in some cases it doesn't work because of the experimental bridge we use between WPF and UWP) - but we felt that it's a little.. weird for the app. Meaning - every action we wanted to let users do through right clicking the app icon on the jump list - like activating a specific effect, or turn on/off devices - don't make sense without actually opening the app. The only thing that makes sense via that menu is start/stopping the current effect. Even when switching an effect it makes more sense to have the app open so you can see the settings for that effect.

I don't know. Minimizing to tray is something that we aren't comfortable with (Microsoft not giving out-of-the-box first-party support for it on their latest UI platforms, trying to get away of it in Windows 10x), and the JumpList is something I think we mind go back to in the not-distant future, when we realize better how to design it. But as for what this issue resembles, minimizing to tray, I don't think we'd take this approach

**Comment by Darkwolf1515** [comment]
Primarily I just wanted it not for control but so I don't always have it in the task bar, like other background software thanks for trying however
