### ISSUE TITLE
Install Problem 

### ISSUE THREAD

**Issue by Ajam1997** [rgb-master-team/RGBMaster#39]
Whenever I run the signandinstallapp I get the following, this happens if I run it as admin as well.
![Capture](https://user-images.githubusercontent.com/43974482/105440788-723b5080-5c24-11eb-8158-007730a27ee2.JPG)

**Comment by benbense** [comment]
Can you provide a screenshot of the folder that you have extracted the files to please

**Comment by deankevorkian** [comment]
I think it's because the current working directory, while should be D:/alexa/... Etc., still points to C:/. The first line on our batch script runs a cd to point on the folder of the installation script (which is on D) but the cmd is at C, I think it's an issue on our end

He either has to put that folder on C:/ (the extracted folder) and then try, or wait for us to provide a fix

**Comment by deankevorkian** [comment]
Hey @Ajam1997 can you try to run this `.bat` file instead? (Place him on the same extracted path of the `.rar` file)

https://filebin.net/b93ugteqmjqh9gid

**Comment by Ajam1997** [comment]
Thanks, guys, I moved the directory and it installed fine
