### ISSUE TITLE
Razer not detecting Asus aura devices

### ISSUE THREAD

**Issue by infideleraser** [rgb-master-team/RGBMaster#54]
I installed the script correctly and it worked for a while, but i had to uninstall razer synapse and reinstall it and now it gives an error in chroma connect

![image](https://user-images.githubusercontent.com/41710105/146687743-4741abe7-f717-45c1-a00a-4014a5c2aca0.png)

**Comment by infideleraser** [comment]
![image](https://user-images.githubusercontent.com/41710105/146687755-cace4a41-a8bc-4b3d-abc6-6a3d649bbf4f.png)
larger screenshot

**Comment by deankevorkian** [comment]
Hey! I'm trying to guess from the details you provided because I still lack some - it seems like you've been using https://github.com/AndrewBabbitt97/AuraConnect for having ASUS devices appear in Synapse, right?
If that's the case, it seems that has been archived and you need to get this instead - 
https://github.com/ChromaControl/ChromaControl
I've personally tried it with RGBMaster and it seems to be working fine.
Keep in mind you need to have Aura app and the Chroma Connect apps running.
I'm hoping to be able to natively provide support for Aura in the future so you wouldn't need to go through workarounds such as this.

**Comment by deankevorkian** [comment]
Closing this for being stale/inactive, lmk if I should reopen
