### ISSUE TITLE
Code has to be fault-tolerant

### ISSUE THREAD

**Issue by benbense** [rgb-master-team/RGBMaster#6]
... but act accordingly and disconnect a device when it stops/fails to respond, etc..
So we have to update the displayed list of devices, stop trying to sync to it, inform the user that the connection has been lost, allow reconnection to the faulted device...

This will be taken care of when we re-write the client.

**Comment by deankevorkian** [comment]
logs and writings merged into master, we now need to add a couple more treatments to unhandled exceptions from the ui, background tasks, and the complete appdomain, and log them. additionally we must trace all cases where the app can crash... if there are any sensitive parts that may not be accessed more than once concurrently due to SDK limitations we should keep using mechanisms that will allow us to asynchronously "lock" sensitive code parts but not pause or freeze the main thread. anyways, this is a work in progress

**Comment by deankevorkian** [comment]
Code is fault tolerant enough atm; closing this to set logging as another issue
